worker_processes 1;
error_log /dev/stderr info;
events { worker_connections 1024; }
http {
  server {
    listen 8091;
    server_name _;
    location / {
      rewrite_by_lua_block {
        ngx.ctx.is_login = (ngx.req.get_method() == "POST" and ngx.var.uri == "/api/v2/auth/login")
      }
      proxy_pass http://192.168.2.90:8086;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      header_filter_by_lua_block {
        if ngx.ctx.is_login and ngx.status == 204 then
          ngx.header.content_length = "3"
          ngx.status = 200
          ngx.ctx.login_rewrite = true
        end
      }
      body_filter_by_lua_block {
        if ngx.ctx.login_rewrite and ngx.arg[2] then
          ngx.arg[1] = "Ok."
        end
      }
    }
  }
}