services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=America/Montevideo
    volumes:
      - ./config:/config
    ports:
      - "8123:8123"
    restart: unless-stopped
