services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - /mnt/Download/Flix/series:/series:ro
      - /mnt/Download/Flix/series-espanol:/series-espanol:ro
      - /mnt/Download/Flix/peliculas:/peliculas:ro
      - /mnt/Download/Flix/peliculas-espanol:/peliculas-espanol:ro
      - /mnt/Download/YouTube:/youtube:ro
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "107"