services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    volumes:
      - ./config:/config
      - /mnt/Download/Flix/series:/series
      - /mnt/Download/Flix/peliculas:/peliculas
    ports:
      - "6767:6767"
    restart: unless-stopped
